Fix jaeger labels selector (#62)
We were rendering duplicated labels `app.kubernetes.io/component` and `app.kubernetes.io/name` in jaeger `deploy` and `svc`. This is causing problems when piping rendered output to `kustomize`. 

```
stomize-chart/kustomize. error output:
Error: received error yaml: unmarshal errors:
  line 29: mapping key "app.kubernetes.io/name" already defined at line 27 for the following resource:
```

This PR 

- cleans up all these duplicated labels.
- enforce consistency to some extent without introducing any breaking change
  - use `app.kubernetes.io/component: all-in-one` and `app.kubernetes.io/name: jaeger` as much as possible. They are the value of `matchLabels` right now and we can't change them, so we might as well use them as the standard for all jaeger components.

See below comment for the latest diff

### Test plan

<!--
  As part of SOC2/GN-104 and SOC2/GN-105 requirements, all pull requests are REQUIRED to
  provide a "test plan". A test plan is a loose explanation of what you have done or
  implemented to test this, as outlined in our Testing principles and guidelines:
  https://docs.sourcegraph.com/dev/background-information/testing_principles
  Write your test plan here after the "Test plan" header.
-->

Deploy the chart from the last release

```sh
helm upgrade --install -n sourcegraph -f ./override.yaml sourcegraph sourcegraph/sourcegraph
```

Inspect the diff, jaeger deployment and services should no longer contain duplicate labels.

```sh
helm diff -n sourcegraph -f ./override.yaml sourcegraph charts/sourcegraph/.
```

Deploy the changes make sure it's non-breaking

```sh
helm upgrade --install -n sourcegraph -f ./override.yaml sourcegraph charts/sourcegraph/.
```

Of course, verify tracing still works